'use strict';

const HTTP_STATUS_OK           = 200
    , HTTP_STATUS_NOT_MODIFIED = 304
    , HTTP_STATUS_NOT_FOUND    = 404;

module.exports = {
	HTTP_STATUS_OK,
	HTTP_STATUS_NOT_FOUND,
	HTTP_STATUS_NOT_MODIFIED
};